# conda env create --file environment.yml
# mamba env create --file environment.yml
name: gch4i
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyarrow
  - gdal
  - rasterio
  - geopandas
  - fiona
  # - basemap # added by Nathan -- needed for module data_plot_functions (in "Global_Functions")
  - black
  - cartopy
  - dask
  - xlrd # added by Hannah -- needed in Coal and lng_storage_proxy and Roads
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  # - missingno
  # - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pyxlsb
  # - plotly
  # - pyjanitor
  - pylint
  - pyodbc # added by Nathan -- needed in Wastewater
  - pyprojroot
  # - pyshp # added by Hannah -- needed in Petroleum Systems
  - python-duckdb
  - python-dotenv
  # - scikit-learn
  - seaborn
  - netCDF4
  - xarray
  - openpyxl
  # - tabula-py
  # - pyodbc
  - geopy
  # - PyPDF2
  - pytask
  - geocube
  - pyogrio # use
  - rioxarray
  - pip
  # - osgeo
  - xlsxwriter
  - lxml
  - pip:
      - -e . # this will install the gch4i package in your environment in dev mode
