"""
Author:     Nick Kruskamp
Created:    2021-10-07
Purpose:    To identify non-ASCII characters in a file and print their positions.
            We were having issues with setup.py using the readme file as the long
            description for the package. I wanted to find the non-ASCII characters.
            This script was generated by Co-Pilot and edited to fit my needs.
"""

# %%
import re
from pathlib import Path

# Define the path to the file
file_path = Path().cwd() / "README.md"

# Read the content of the file
with open(file_path, "r", encoding="utf-8") as file:
    lines = file.readlines()

content = "".join(lines)

# Find all non-ASCII characters
non_ascii_chars = re.findall(r"[^\x00-\x7F]", content)

# Print the non-ASCII characters
print("Non-ASCII characters found:", non_ascii_chars)

# Find and print non-ASCII characters with their positions
for line_num, line in enumerate(lines, start=1):
    for match in re.finditer(r"[^\x00-\x7F]", line):
        char = match.group()
        col_num = match.start() + 1
        print(
            f"Non-ASCII character '{char}' found at line {line_num}, column {col_num}"
        )
# %%
